/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppClassesIndexRouteImport } from './routes/app.classes.index'
import { Route as AppClassesCategoryIdRouteImport } from './routes/app.classes.$categoryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesIndexRoute = AppClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesCategoryIdRoute = AppClassesCategoryIdRouteImport.update({
  id: '/classes/$categoryId',
  path: '/classes/$categoryId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/classes/$categoryId': typeof AppClassesCategoryIdRoute
  '/app/classes/': typeof AppClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/app/classes/$categoryId': typeof AppClassesCategoryIdRoute
  '/app/classes': typeof AppClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/classes/$categoryId': typeof AppClassesCategoryIdRoute
  '/app/classes/': typeof AppClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/app' | '/app/' | '/app/classes/$categoryId' | '/app/classes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/classes/$categoryId' | '/app/classes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/'
    | '/app/classes/$categoryId'
    | '/app/classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes/': {
      id: '/app/classes/'
      path: '/classes'
      fullPath: '/app/classes/'
      preLoaderRoute: typeof AppClassesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes/$categoryId': {
      id: '/app/classes/$categoryId'
      path: '/classes/$categoryId'
      fullPath: '/app/classes/$categoryId'
      preLoaderRoute: typeof AppClassesCategoryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClassesCategoryIdRoute: typeof AppClassesCategoryIdRoute
  AppClassesIndexRoute: typeof AppClassesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClassesCategoryIdRoute: AppClassesCategoryIdRoute,
  AppClassesIndexRoute: AppClassesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
